config/routes.rb
Rails.application.routes.draw do
  
  resources :passdowns

  resources :tickets

  get "tickets/index"
  get "tickets/new"
  get "tickets/edit"
  get "tickets/show"
  resources :inventory_types

  resources :statuses

  resources :devices

  resources :issue_types

  resources :issue_received_methods

  resources :ticket_issues

  resources :computer_images

  resources :computer_models

  resources :employees

  resources :copy_centers

  resources :locations

  resources :ps_connection_informations

  devise_for :users
  get "welcome/index"
  get "admin/index"

  resources :inventory

  resources :printers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :computers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :print_stations do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end

  resources :tickets do
    resources :ticket_issues
    resources :comments
  end

  resources :printer_models

  authenticated :user do 
    root to: redirect('welcome/index'), as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/print_station.rb
class PrintStation < ActiveRecord::Base
  has_many :printers, through: :ps_connection_informations
  has_many :ps_connection_informations
  has_many :inventories, through: :printers
  has_one :computer
  has_many :tickets, as: :ticketable
  has_many :comments, as: :commentable
  belongs_to :status, class_name: 'Status', foreign_key: 'status_id'
  belongs_to :copy_center
  validates_presence_of :location_id, :location

  default_scope { order ('print_stations.location_id ASC') }

end

app/controllers/print_stations_controller.rb
class PrintStationsController < ApplicationController
  before_action :set_print_station, only: [:show, :edit, :update, :destroy]

  # GET /print_stations
  # GET /print_stations.json
  def index
    @print_stations = PrintStation.all
    @statuses = Status.all
  end

  # GET /print_stations/1
  # GET /print_stations/1.json
  def show
    @print_station = PrintStation.find(params[:id])
    @commentable = @print_station
    @comments = @commentable.comments
    @comment = Comment.new
    @ticketable = @print_station
    @tickets = @ticketable.tickets
    @ticket = Ticket.new
  end

  # GET /print_stations/new
  def new
    @print_station = PrintStation.new
  end

  # GET /print_stations/1/edit
  def edit
  end

  # POST /print_stations
  # POST /print_stations.json
  def create
    @print_station = PrintStation.new(print_station_params)

    respond_to do |format|
      if @print_station.save
        format.html { redirect_to @print_station, notice: 'Print station was successfully created.' }
        format.json { render action: 'show', status: :created, location: @print_station }
      else
        format.html { render action: 'new' }
        format.json { render json: @print_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /print_stations/1
  # PATCH/PUT /print_stations/1.json
  def update
    respond_to do |format|
      if @print_station.update(print_station_params)
        format.html { redirect_to @print_station, notice: 'Print station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @print_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /print_stations/1
  # DELETE /print_stations/1.json
  def destroy
    @print_station.destroy
    respond_to do |format|
      format.html { redirect_to print_stations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_print_station
      @print_station = PrintStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def print_station_params
      params.require(:print_station).permit(:location_id, :location, :building, :room_number, :computer_jack, :printer_our_jack, :computer_our_jack, :strapped_down, :restricted_access, :key_code, :keyboard, :mouse, :touchpad, :monitor, :status_id, :copy_center_id)
    end
end

app/helpers/print_stations_helper.rb
module PrintStationsHelper

  def checked(input)
    if input == true
      return 'btn btn-primary active'
    else
      return 'btn btn-primary'
    end
  end

  def is_there(item)
    if item
      return 'glyphicon glyphicon-ok'
    else
      return 'glyphicon glyphicon-remove'
    end
  end

  def check_status(print_station)
    if print_station == 'Active'
      return 'panel-success'
    elsif print_station == 'Down'
      return 'panel-danger'
    elsif print_station == 'Removed'
      return 'panel-danger'
    else
      return 'panel-warning'
    end
  end

  def copy_center(print_station)
    if print_station.copy_center.nil?
      return "None Assigned"
    else
      html = link_to @print_station.copy_center.location, copy_center_path(@print_station.copy_center)
    end
  end

end

app/views/print_stations/_computer_info.html.haml
.panel.panel-info
  .panel-heading
    %h4 Computer
  - if @print_station.computer
    %table.table.table-condensed.table-striped.table-hover
      %tbody{style: 'font-size:14px'}
        %tr
          %th Service Tag:
          %td= link_to @print_station.computer.service_tag, computer_path(@print_station.computer) unless @print_station.computer.nil?
        %tr
          %th Image:
          - if @print_station.computer.computer_image
            %td= @print_station.computer.computer_image.image
          - else
            %td
              %strong Needs to be added
  - else
    .well.well-sm
      %strong No computer associated with #{ @print_station.location }

app/views/print_stations/_form.html.haml
= simple_form_for @print_station, defaults:{ label:false } do |f|
  .row
    .col-lg-4.col-lg-offset-4
      .form-group
        %label.control-label Status
        =f.input :status_id, collection: Status.all, label_method: :status, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Support Center
        =f.input :copy_center_id, collection: CopyCenter.all, label_method: :location, input_html:{class: 'form-control'}
  .row
    .col-lg-4.col-lg-offset-2
      .form-group
        %label.control-label Location ID
        =f.input :location_id, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Location
        =f.input :location, input_html:{class: 'form-control'}
    .col-lg-4
      .form-group
        %label.control-label Building
        =f.input :building, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Room Number
        =f.input :room_number, input_html:{class: 'form-control'}
  .row
    .col-lg-4.col-lg-offset-2
      .btn-group{data:{toggle: 'buttons'}}
        %label.control-label{class: checked(@print_station.printer_our_jack)}
          Our Printer Jack
          =f.input :printer_our_jack, input_html:{class: 'hidden', type: 'checkbox', checked: true}
        %label.control-label{class: checked(@print_station.computer_our_jack)}
          Our Computer Jack
          =f.input :computer_our_jack, input_html:{class: 'hidden', type: 'checkbox'}
    .col-lg-4
      .form-group
        =f.input :computer_jack, placeholder: 'Computer Jack number', input_html:{class: 'form-control'}
  .row
    .col-lg-4.col-lg-offset-2
      .btn-group{data:{toggle: 'buttons'}}
        %label.control-label{class: checked(@print_station.strapped_down)}
          Strapped Down
          =f.input :strapped_down, input_html:{class: 'hidden',type: 'checkbox'}
        %label.control-label{class: checked(@print_station.restricted_access)}
          Restricted Access Lab
          =f.input :restricted_access, input_html:{class: 'hidden',type: 'checkbox'}
    .col-lg-4
      .form-group
        =f.input :key_code, placeholder: 'Door key code', input_html:{class: 'form-control'}
  .row
    .col-lg-4.col-lg-offset-2
      .btn-group{data:{toggle: 'buttons'}}
        %label.control-label{class: checked(@print_station.keyboard)}
          Keyboard
          =f.input :keyboard, input_html:{class: 'hidden', type: 'checkbox'}
        %label.control-label{class: checked(@print_station.mouse)}
          Mouse
          =f.input :mouse, input_html:{class: 'hidden', type: 'checkbox'}
        %label.control-label{class: checked(@print_station.touchpad)}
          Touchpad
          =f.input :touchpad, input_html:{class: 'hidden', type: 'checkbox'}
    .col-lg-4
      .form-group
        =f.input :monitor, placeholder: 'Monitor type', input_html:{class: 'form-control'}
  .row
    .text-center
      .btn-group
        = f.button :submit, 'Save', class: 'btn btn-primary'
        = link_to 'Back', print_stations_path, class: 'btn btn-primary'

app/views/print_stations/_info.html.haml
.row
  .col-md-8
    .btn-group
      = link_to print_stations_path, class: 'btn btn-sm btn-default' do
        %i.glyphicon.glyphicon-arrow-left
      = link_to edit_print_station_path(@print_station), class: 'btn btn-sm btn-default' do
        %i.glyphicon.glyphicon-pencil
%hr
.row
  .col-lg-4
    = render 'show_info'
  .col-lg-4
    = render 'printer_info'
    = render 'computer_info'
  .col-lg-4
    = render 'inventory_info'

app/views/print_stations/_inventory_info.html.haml
.panel.panel-info
  .panel-heading
    %h4 Supplies
  - @print_station.inventories.each do |inventory|
    %table.table.table-condensed.table-striped.table-hover
      %tbody{style: 'font-size:14px'}
        %tr{style: 'font-size:16px'}
          %th Inventory Number:
          %td= link_to inventory.id, inventory_path(inventory)
        %tr
          %th Type:
          %td= inventory.inventory_type.inv_type
        %tr
          %th Location:
          %td= link_to inventory.location.location, location_path(inventory.location)
        %tr
          %th Printer:
          %td= link_to inventory.printer.serial_number, printer_path(inventory.printer)
        %tr
          %th Printer Model:
          %td= inventory.printer.printer_model.model
    - if @print_station.inventories.count > 1
      %br

app/views/print_stations/_printer_info.html.haml
.panel.panel-info
  .panel-heading
    %h4 Printer
  - @print_station.ps_connection_informations.each do |ps_info|
    - if ps_info.printer
      %table.table.table-condensed.table-striped.table-hover
        %tbody{style: 'font-size:14px'}
          %tr{style: 'font-size:16px'}
            %th Serial Number:
            %td= link_to ps_info.printer.serial_number, printer_path(ps_info.printer)
          %tr
            %th B&W / Color:
            %td= nice_color ps_info.printer.color_bw
          %tr
            %th Model:
            %td= link_to ps_info.printer.printer_model.model, printer_model_path(ps_info.printer.printer_model_id)
          %tr
            %th IP Address:
            %td= link_to ps_info.ip_address, ps_connection_information_path(ps_info)
          %tr
            %th Jack:
            %td= ps_info.jack
      - if @print_station.ps_connection_informations.count > 1
        %br
    - else
      .well.well-sm
        %strong
          No Printer Assigned IP Address
          = link_to ps_info.ip_address, ps_connection_information_path(ps_info)

app/views/print_stations/_show_info.html.haml
.panel{class: check_status(@print_station.status.status)}
  .panel-heading
    %h4
      #{ @print_station.location }
      .pull-right= @print_station.status.status
  %table.table.table-condensed.table-striped.table-hover
    %tbody{style: 'font-size:14px'}
      %tr
        %th Location ID:
        %td= @print_station.location_id
      %tr
        %th Building:
        %td= @print_station.building
      %tr
        %th Room number:
        %td= @print_station.room_number
      %tr
        %th Our Printer Jack:
        %td
          %span{class: is_there(@print_station.printer_our_jack)}
      %tr
        %th Our Computer Jack:
        %td
          %span{class: is_there(@print_station.computer_our_jack)}
      %tr
        %th Computer Jack Number:
        %td= @print_station.computer_jack
      %tr
        %th Strapped down:
        %td
          %span{class: is_there(@print_station.strapped_down)}
      %tr
        %th Restricted Access:
        %td
          %span{class: is_there(@print_station.restricted_access)}
      - if @print_station.restricted_access
        %tr
          %th Key Code:
          %td= @print_station.key_code
      %tr
        %th Keyboard:
        %td
          %span{class: is_there(@print_station.keyboard)}
      %tr
        %th Mouse:
        %td
          %span{class: is_there(@print_station.mouse)}
      %tr
        %th Touchpad:
        %td
          %span{class: is_there(@print_station.touchpad)}
      %tr
        %th Monitor:
        - if @print_station.monitor == ""
          %td
            %strong needs to be recorded
        - else
          %td= @print_station.monitor

app/views/print_stations/edit.html.haml
.text-center
  %h1 Edit Print Station
= render 'form'

app/views/print_stations/index.html.haml
%h1 Print Stations
= link_to new_print_station_path, class: 'btn btn-primary' do
  %i.glyphicon.glyphicon-plus
  Print Station
%hr
.panel.panel-danger
  .panel-heading
    Down Stations
  %table.table.table-hover
    %thead
      %tr
        %th Location ID
        %th Location
        %th Building
        %th Room number
        %th Copy Center
        %th
    %tbody
      - @print_stations.each do |print_station|
        - if print_station.status.status == "Down"
          %tr
            %td= link_to print_station.location_id, print_station_path(print_station)
            %td= print_station.location
            %td= print_station.building
            %td= print_station.room_number
            %td= link_to print_station.copy_center.location, copy_center_path(print_station.copy_center) unless print_station.copy_center.nil?
            %td
              = link_to edit_print_station_path(print_station), class: 'btn-sm' do
                %i.glyphicon.glyphicon-pencil
              = link_to print_station, method: :delete, data: { confirm: 'Make sure to remove all IP Addresses before deleting Print Station' }, class: 'btn-sm' do
                %i.glyphicon.glyphicon-trash
%hr
.panel.panel-primary
  .panel-heading
    Active Stations
  %table.table.table-hover
    %thead
      %tr
        %th Location ID
        %th Location
        %th Building
        %th Room number
        %th Copy Center
        %th
    %tbody
      - @print_stations.each do |print_station|
        - if print_station.status.status == "Active"
          %tr
            %td= link_to print_station.location_id, print_station_path(print_station)
            %td= print_station.location
            %td= print_station.building
            %td= print_station.room_number
            %td= link_to print_station.copy_center.location, copy_center_path(print_station.copy_center) unless print_station.copy_center.nil?
            %td
              = link_to edit_print_station_path(print_station), class: 'btn-sm' do
                %i.glyphicon.glyphicon-pencil
              = link_to print_station, method: :delete, data: { confirm: 'Make sure to remove all IP Addresses before deleting Print Station' }, class: 'btn-sm' do
                %i.glyphicon.glyphicon-trash
%hr
.panel.panel-warning
  .panel-heading
    Suspended Stations
  %table.table.table-hover
    %thead
      %tr
        %th Location ID
        %th Location
        %th Building
        %th Room number
        %th Copy Center
        %th
    %tbody
      - @print_stations.each do |print_station|
        - if print_station.status.status == "Suspended"
          %tr
            %td= link_to print_station.location_id, print_station_path(print_station)
            %td= print_station.location
            %td= print_station.building
            %td= print_station.room_number
            %td= link_to print_station.copy_center.location, copy_center_path(print_station.copy_center) unless print_station.copy_center.nil?
            %td
              = link_to edit_print_station_path(print_station), class: 'btn-sm' do
                %i.glyphicon.glyphicon-pencil
              = link_to print_station, method: :delete, data: { confirm: 'Make sure to remove all IP Addresses before deleting Print Station' }, class: 'btn-sm' do
                %i.glyphicon.glyphicon-trash
%hr
.panel.panel-danger
  .panel-heading
    Removed Stations
  %table.table.table-hover
    %thead
      %tr
        %th Location ID
        %th Location
        %th Building
        %th Room number
        %th Copy Center
        %th
    %tbody
      - @print_stations.each do |print_station|
        - if print_station.status.status == "Removed"
          %tr
            %td= link_to print_station.location_id, print_station_path(print_station)
            %td= print_station.location
            %td= print_station.building
            %td= print_station.room_number
            %td= link_to print_station.copy_center.location, copy_center_path(print_station.copy_center) unless print_station.copy_center.nil?
            %td
              = link_to edit_print_station_path(print_station), class: 'btn-sm' do
                %i.glyphicon.glyphicon-pencil
              = link_to print_station, method: :delete, data: { confirm: 'Make sure to remove all IP Addresses before deleting Print Station' }, class: 'btn-sm' do
                %i.glyphicon.glyphicon-trash

app/views/print_stations/new.html.haml
.text-center
  %h1 New Print Station
= render 'form'

app/views/print_stations/show.html.haml
.row
  .col-md-8
    %ul#myTab.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#print_station"} Print Station Information
      %li
        %a{"data-toggle" => "tab", :href => "#ticket"} Ticket Info
  .col-md-4
    %h4
      Support Center:
      = copy_center(@print_station)
.row
  .col-md-12
    .tab-content
      #print_station.tab-pane.active
        %br
        =render 'info'
        %hr
        .row
          .col-md-9
            =render 'comments/list'
          =render 'comments/form'
      #ticket.tab-pane
        / =render 'tickets/list'
        %br
        =render 'tickets/open_tickets'
        =render 'tickets/resolved_tickets'
        =render 'tickets/form'