config/routes.rb
Rails.application.routes.draw do
  
  resources :passdowns

  resources :tickets

  get "tickets/index"
  get "tickets/new"
  get "tickets/edit"
  get "tickets/show"
  resources :inventory_types

  resources :statuses

  resources :devices

  resources :issue_types

  resources :issue_received_methods

  resources :ticket_issues

  resources :computer_images

  resources :computer_models

  resources :employees

  resources :copy_centers

  resources :locations

  resources :ps_connection_informations

  devise_for :users
  get "welcome/index"
  get "admin/index"

  resources :inventory

  resources :printers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :computers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :print_stations do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end

  resources :tickets do
    resources :ticket_issues
    resources :comments
  end

  resources :printer_models

  authenticated :user do 
    root to: redirect('welcome/index'), as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :employee

  default_scope { order ('comments.created_at DESC') }

end

app/models/computer.rb
class Computer < ActiveRecord::Base
  validates :service_tag, presence:true
  belongs_to :computer_image
  belongs_to :computer_model
  belongs_to :print_station
  has_many :tickets, as: :ticketable
  has_many :comments, as: :commentable
end

app/models/computer_image.rb
class ComputerImage < ActiveRecord::Base
	has_many :computers
end

app/models/computer_model.rb
class ComputerModel < ActiveRecord::Base
	has_many :computers
end

app/models/copy_center.rb
class CopyCenter < ActiveRecord::Base
	has_many :employees
  has_many :print_stations
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :issue_types
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	belongs_to :copy_center
  has_many :tickets
  has_many :comments
  has_many :passdowns
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :printer
  belongs_to :location
  belongs_to :printer_model
  belongs_to :inventory_type
  
	validates :inventory_type_id, presence: true
	validates :location, presence: true

  LOCATIONS = {
    jfsbcc: 'JFSB CC',
    cougarcreations: 'Cougar Creations',
    upb: 'UPB', 
    intransit: 'In Transit'
  }
end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
  belongs_to :device
  has_many :ticket_issues

  default_scope { order ('issue_types.device_id ASC, issue_types.issue ASC') }

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :inventories
end

app/models/passdown.rb
class Passdown < ActiveRecord::Base
  belongs_to :employee

  default_scope { order ('passdowns.created_at DESC') }

end

app/models/print_station.rb
class PrintStation < ActiveRecord::Base
  has_many :printers, through: :ps_connection_informations
  has_many :ps_connection_informations
  has_many :inventories, through: :printers
  has_one :computer
  has_many :tickets, as: :ticketable
  has_many :comments, as: :commentable
  belongs_to :status, class_name: 'Status', foreign_key: 'status_id'
  belongs_to :copy_center
  validates_presence_of :location_id, :location

  default_scope { order ('print_stations.location_id ASC') }

end

app/models/printer.rb
class Printer < ActiveRecord::Base
  has_many :inventories
  has_many :tickets, as: :ticketable
  has_many :comments, as: :commentable
  belongs_to :ps_connection_information
  belongs_to :printer_model
  validates :serial_number, presence:true

  default_scope { order ('printers.printer_model_id ASC, printers.serial_number ASC') }

  COLORS = {
    color: 'Color',
    bw: 'B&W'
  }
end

app/models/printer_model.rb
class PrinterModel < ActiveRecord::Base
  has_many :printers
  has_many :inventories
  validates :model, presence:true
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :print_stations
end

app/models/ticket(old).rb
class Ticket < ActiveRecord::Base
  belongs_to :created, class_name: 'Employee', foreign_key: 'created_employee_id'
  belongs_to :completed, class_name: 'Employee', foreign_key: 'completed_employee_id'
  belongs_to :ticketable, polymorphic: true
  belongs_to :issue_received_method
  has_many :ticket_issues
  has_many :comments, as: :commentable

  accepts_nested_attributes_for :ticket_issues, :allow_destroy => true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :ticketable, polymorphic: true
  belongs_to :created, class_name: 'Employee', foreign_key: 'created_employee_id'
  has_many :ticket_issues, dependent: :destroy
  has_many :comments, as: :commentable

  validates :created_employee_id, presence: true

  accepts_nested_attributes_for :ticket_issues, :allow_destroy => true

  default_scope { order ('tickets.id DESC') }


end

app/models/ticket_issue.rb
class TicketIssue < ActiveRecord::Base
  belongs_to :tickets
  belongs_to :issue_type
  belongs_to :issue_received_method
  has_many :comments, as: :commentable
  belongs_to :resolved, class_name: 'Employee', foreign_key: 'resolved_employee_id'

  validates :issue_type_id, presence: true
  validates :issue_received_method_id, presence: true

  # LEVELS = {
  #   high: 'High'
  #   normal: 'Normal'
  #   low: 'Low'
  # }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

#### This is the correct method you override with the code above
#### def self.find_for_database_authentication(warden_conditions)
#### end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/views/admin/index.html.haml
.page-header
  %h1 Admin
.row
  .col-lg-2
    %ul#myTab.nav.nav-pills.nav-stacked
      %li.active
        %a{"data-toggle" => "tab", :href => "#support_center"} Support Centers
      %li
        %a{"data-toggle" => "tab", :href => "#employee"} Employees
      %li
        %a{"data-toggle" => "tab", :href => "#toner_location"} Toner Locations
      %li
        %a{"data-toggle" => "tab", :href => "#inventory_type"} Supply Types
      %li
        %a{"data-toggle" => "tab", :href => "#computer_model"} Computer Models
      %li
        %a{"data-toggle" => "tab", :href => "#computer_image"} Computer Images
      %li
        %a{"data-toggle" => "tab", :href => "#printer_model"} Printer Models
      %li
        %a{"data-toggle" => "tab", :href => "#ps_connection_information"} Print Station Connection Info
      %li
        %a{"data-toggle" => "tab", :href => "#devices"} Ticket Devices
      %li
        %a{"data-toggle" => "tab", :href => "#received_methods"} Issue Reception Methods
      %li
        %a{"data-toggle" => "tab", :href => "#issue_types"} Issue Types
      %li
        %a{"data-toggle" => "tab", :href => "#print_station_status"} Print Station Status
  .col-lg-10
    .tab-content
      #support_center.tab-pane.active
        = render 'layouts/copy_center'
        = link_to new_copy_center_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Support Center
      #employee.tab-pane
        = render 'layouts/employee'
        = link_to new_employee_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Employee
      #toner_location.tab-pane
        = render 'layouts/toner_location'
        = link_to new_location_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Location
      #inventory_type.tab-pane
        = render 'layouts/inventory_type'
        = link_to new_inventory_type_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Type
      #computer_model.tab-pane
        = render 'layouts/computer_model'
        = link_to new_computer_model_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Model
      #computer_image.tab-pane
        = render 'layouts/computer_image'
        = link_to new_computer_image_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Computer Image
      #printer_model.tab-pane
        = render 'layouts/printer_models'
        = link_to new_printer_model_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Printer Model
      #ps_connection_information.tab-pane
        = render 'layouts/ps_connection_information'
        = link_to new_ps_connection_information_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Connection
      #devices.tab-pane
        = render 'layouts/device'
        = link_to new_device_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Device
      #received_methods.tab-pane
        = render 'layouts/received_methods'
        = link_to new_issue_received_method_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Method
      #issue_types.tab-pane
        = render 'layouts/issue_types'
        = link_to new_issue_type_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Issue Types
      #print_station_status.tab-pane
        = render 'layouts/print_station_status'
        = link_to new_status_path, class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-plus
          Status

app/views/tickets(old)/_form.html.haml
= simple_form_for @ticket, defaults:{ label:false } do |f|
  .row
    .col-lg-4.col-lg-offset-4
      .form-group
        %label.control-label Created by:
        = f.input :created_employee_id, collection: Employee.all, label_method: :name, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Received Method:
        = f.input :issue_received_method_id, collection: IssueReceivedMethod.all, label_method: :method, input_html:{class: 'form-control'}
      .text-center
        .btn-group
          = f.button :submit, 'Save', class: 'btn btn-primary'
          = link_to 'Back', tickets_path, class: 'btn btn-primary'

app/views/tickets(old)/edit.html.haml
.text-center
  %h1 Edit Ticket
= render 'form'

app/views/tickets(old)/index.html.haml
%h1 Tickets
= link_to new_ticket_path, class: 'btn btn-primary' do
  %i.glyphicon.glyphicon-plus
  Ticket
%table.table.table-hover.table-striped
  %thead
    %tr
      %th Ticket ID
      %th Device
      %th Created By
      %th Created Date
      %th Completed By
      %th Completed Date
      %th
  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.id, ticket_path(ticket)
        %td= ticket.device_id
        %td= ticket.created.name
        %td= ticket.created_at.strftime("%B %d, %Y")
        %td= ticket.completed.name unless ticket.completed.nil?
        %td= ticket.completed_at.strftime("%B %d, %Y") unless ticket.completed_at.nil?
        %td
          = link_to edit_ticket_path(ticket), class: 'btn-sm' do
            %i.glyphicon.glyphicon-pencil
          = link_to ticket, method: :delete, data: { confirm: 'Are you sure?' }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm' do
            %i.glyphicon.glyphicon-trash

app/views/tickets(old)/new.html.haml
.text-center
  %h1 New Ticket
= render 'form'

app/views/tickets(old)/show.html.haml
.row
  .btn-group
    = link_to tickets_path, class: 'btn btn-sm btn-default' do
      %i.glyphicon.glyphicon-arrow-left
    = link_to edit_ticket_path(@ticket), class: 'btn btn-sm btn-default' do
      %i.glyphicon.glyphicon-pencil
  %hr
.row
  .col-lg-4
    .panel.panel-primary
      .panel-heading
        %h4 Ticket Info
      .panel-body
        %p
          %strong Created by:
          = @ticket.created.name unless @ticket.created.nil?
        %p
          %strong Created on:
          =@ticket.created_at.strftime("%B %d, %Y")
        %p
          %strong Completed by:
          = @ticket.completed.name unless @ticket.completed.nil?
        %p
          %strong Completed at:
          = @ticket.completed_at.strftime("%B %d, %Y") unless @ticket.completed_at.nil?
        %p
          %strong Issue received method:
          = @ticket.issue_received_method.method
%hr
.row
  .col-lg-9
    =render 'comments/list'
  =render 'comments/form'