config/routes.rb
Rails.application.routes.draw do
  
  resources :passdowns

  resources :tickets

  get "tickets/index"
  get "tickets/new"
  get "tickets/edit"
  get "tickets/show"
  resources :inventory_types

  resources :statuses

  resources :devices

  resources :issue_types

  resources :issue_received_methods

  resources :ticket_issues

  resources :computer_images

  resources :computer_models

  resources :employees

  resources :copy_centers

  resources :locations

  resources :ps_connection_informations

  devise_for :users
  get "welcome/index"
  get "admin/index"

  resources :inventory

  resources :printers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :computers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :print_stations do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end

  resources :tickets do
    resources :ticket_issues
    resources :comments
  end

  resources :printer_models

  authenticated :user do 
    root to: redirect('welcome/index'), as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/printer_model.rb
class PrinterModel < ActiveRecord::Base
  has_many :printers
  has_many :inventories
  validates :model, presence:true
end

app/controllers/printer_models_controller.rb
class PrinterModelsController < ApplicationController
  before_action :set_printer_model, only: [:show, :edit, :update, :destroy]

  # GET /printer_models
  # GET /printer_models.json
  def index
    @printer_models = PrinterModel.all
  end

  # GET /printer_models/1
  # GET /printer_models/1.json
  def show
  end

  # GET /printer_models/new
  def new
    @printer_model = PrinterModel.new
  end

  # GET /printer_models/1/edit
  def edit
  end

  # POST /printer_models
  # POST /printer_models.json
  def create
    @printer_model = PrinterModel.new(printer_model_params)

    respond_to do |format|
      if @printer_model.save
        format.html { redirect_to @printer_model, notice: 'Printer model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @printer_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @printer_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printer_models/1
  # PATCH/PUT /printer_models/1.json
  def update
    respond_to do |format|
      if @printer_model.update(printer_model_params)
        format.html { redirect_to @printer_model, notice: 'Printer model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @printer_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printer_models/1
  # DELETE /printer_models/1.json
  def destroy
    @printer_model.destroy
    respond_to do |format|
      format.html { redirect_to printer_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer_model
      @printer_model = PrinterModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_model_params
      params.require(:printer_model).permit(:model, :service_code, :black, :cyan, :magenta, :yellow, :fuser, :maint_kit, :transfer_kit, :collection_unit)
    end
end

app/helpers/printer_models_helper.rb
module PrinterModelsHelper
end

app/views/printer_models/_form.html.haml
= simple_form_for @printer_model, defaults:{ label:false } do |f|
  .row
    .col-lg-4.col-lg-offset-4
      .form-group
        %label.control-label Model
        = f.input :model, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Service Code
        = f.input :service_code, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Black
        = f.input :black, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Cyan
        = f.input :cyan, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Magenta
        = f.input :magenta, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Fuser
        = f.input :fuser, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Maint Kit
        = f.input :maint_kit, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Transfer Kit
        = f.input :transfer_kit, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Collection Unit
        = f.input :collection_unit, input_html:{class: 'form-control'}
      .text-center
        .btn-group
          = f.button :submit, 'Save', class: 'btn btn-primary'
          = link_to 'Back', printer_models_path, class: 'btn btn-primary'

app/views/printer_models/_printer_model_info.html.haml
.panel.panel-primary
  .panel-heading
    %h4
      Printer Model Info
      = link_to edit_printer_model_path(@printer_model), class: 'btn btn-sm btn-default pull-right' do
        %i.glyphicon.glyphicon-pencil
  %table.table.table-condensed.table-striped.table-hover
    %tbody{style: 'font-size:14px'}
      %tr
        %th Model:
        %td= @printer_model.model
      %tr
        %th Service code:
        %td= @printer_model.service_code
      %tr
        %th Black:
        %td= @printer_model.black
      %tr
        %th Cyan:
        %td= @printer_model.cyan
      %tr
        %th Magenta:
        %td= @printer_model.magenta
      %tr
        %th Yellow:
        %td= @printer_model.yellow
      %tr
        %th Fuser:
        %td= @printer_model.fuser
      %tr
        %th Maint kit:
        %td= @printer_model.maint_kit
      %tr
        %th Transfer kit:
        %td= @printer_model.transfer_kit
      %tr
        %th Collection unit:
        %td= @printer_model.collection_unit

app/views/printer_models/_printers.html.haml
.panel.panel-success
  .panel-heading
    %h4 Active Printers
  - @printer_model.printers.each do |printer|
    -if printer.ps_connection_information
      %table.table.table-condensed.table-striped.table-hover
        %tbody{style: 'font-size:14px'}
          %tr{style: 'font-size:16px'}
            %th Printer:
            %td= link_to printer.serial_number, printer_path(printer)
          %tr
            %th Location:
            %td= link_to printer.ps_connection_information.print_station.location, print_station_path(printer.ps_connection_information.print_station)
      %br
.panel.panel-warning
  .panel-heading
    %h4 Printers in storage
  - @printer_model.printers.each do |printer|
    -if printer.ps_connection_information.nil?
      %table.table.table-condensed.table-striped.table-hover
        %tbody{style: 'font-size:14px'}
          %tr
            %th Printer:
            %td= link_to printer.serial_number, printer_path(printer)
      %br

app/views/printer_models/edit.html.haml
.container
  .text-center
    %h1 Edit Printer Model
  = render 'form'

app/views/printer_models/index.html.haml
%h1 Printer Models
= link_to new_printer_model_path, class: 'btn btn-primary' do
  %i.glyphicon.glyphicon-plus
  Printer Model
= render 'layouts/printer_models'

app/views/printer_models/new.html.haml
.container
  .text-center
    %h1 New Printer Model
  = render 'form'

app/views/printer_models/show.html.haml
.row
  .col-lg-4
    =render 'printer_model_info'
  .col-lg-3
    =render 'printers'