config/routes.rb
Rails.application.routes.draw do
  
  resources :passdowns

  resources :tickets

  get "tickets/index"
  get "tickets/new"
  get "tickets/edit"
  get "tickets/show"
  resources :inventory_types

  resources :statuses

  resources :devices

  resources :issue_types

  resources :issue_received_methods

  resources :ticket_issues

  resources :computer_images

  resources :computer_models

  resources :employees

  resources :copy_centers

  resources :locations

  resources :ps_connection_informations

  devise_for :users
  get "welcome/index"
  get "admin/index"

  resources :inventory

  resources :printers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :computers do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end
  resources :print_stations do 
    resources :comments
    resources :tickets do
      resources :ticket_issues
      resources :comments
    end
  end

  resources :tickets do
    resources :ticket_issues
    resources :comments
  end

  resources :printer_models

  authenticated :user do 
    root to: redirect('welcome/index'), as: :authenticated_root
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/ps_connection_information.rb
class PsConnectionInformation < ActiveRecord::Base
  belongs_to :print_station
  has_one :printer

  default_scope { order ('ps_connection_informations.print_station_id ASC, ps_connection_informations.ip_address ASC') }

end

app/controllers/ps_connection_informations_controller.rb
class PsConnectionInformationsController < ApplicationController
  before_action :set_ps_connection_information, only: [:show, :edit, :update, :destroy]

  # GET /ps_connection_informations
  # GET /ps_connection_informations.json
  def index
    @ps_connection_informations = PsConnectionInformation.all
  end

  # GET /ps_connection_informations/1
  # GET /ps_connection_informations/1.json
  def show
  end

  # GET /ps_connection_informations/new
  def new
    @ps_connection_information = PsConnectionInformation.new
  end

  # GET /ps_connection_informations/1/edit
  def edit
  end

  # POST /ps_connection_informations
  # POST /ps_connection_informations.json
  def create
    @ps_connection_information = PsConnectionInformation.new(ps_connection_information_params)

    respond_to do |format|
      if @ps_connection_information.save
        format.html { redirect_to @ps_connection_information, notice: 'Ps connection information was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ps_connection_information }
      else
        format.html { render action: 'new' }
        format.json { render json: @ps_connection_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ps_connection_informations/1
  # PATCH/PUT /ps_connection_informations/1.json
  def update
    respond_to do |format|
      if @ps_connection_information.update(ps_connection_information_params)
        format.html { redirect_to @ps_connection_information, notice: 'Ps connection information was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ps_connection_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ps_connection_informations/1
  # DELETE /ps_connection_informations/1.json
  def destroy
    @ps_connection_information.destroy
    respond_to do |format|
      format.html { redirect_to ps_connection_informations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ps_connection_information
      @ps_connection_information = PsConnectionInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ps_connection_information_params
      params.require(:ps_connection_information).permit(:print_station_id, :ip_address, :jack, :pharos)
    end
end

app/helpers/ps_connection_informations_helper.rb
module PsConnectionInformationsHelper
end

app/views/ps_connection_informations/_form.html.haml
= simple_form_for @ps_connection_information, defaults:{ label:false } do |f|
  .row
    .col-lg-4.col-lg-offset-4
      .form-group
        %label.control-label Print Station
        = f.input :print_station_id, collection: PrintStation.all, label_method: :location, input_html:{class: 'form-control'}
      .form-group
        %label.control-label IP Address
        = f.input :ip_address, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Printer Jack
        = f.input :jack, input_html:{class: 'form-control'}
      .form-group
        %label.control-label Pharos Name
        = f.input :pharos, input_html:{class: 'form-control'}
      .text-center
        .btn-group
          = f.button :submit, 'Save', class: 'btn btn-primary'
          = link_to 'Back', admin_index_path, class: 'btn btn-primary'

app/views/ps_connection_informations/_ps_connection_info.html.haml
.panel.panel-primary
  .panel-heading
    %h4 Printer Connection Info
  %table.table.table-condensed.table-striped.table-hover
    %tbody{style: 'font-size:14px'}
      %tr
        %th Print station:
        %td= link_to @ps_connection_information.print_station.location, print_station_path(@ps_connection_information.print_station) unless @ps_connection_information.print_station_id.nil?
      %tr
        %th Ip address:
        %td= @ps_connection_information.ip_address
      %tr
        %th Printer Jack:
        %td= @ps_connection_information.jack
      %tr
        %th Pharos:
        %td= @ps_connection_information.pharos

app/views/ps_connection_informations/edit.html.haml
.text-center
  %h1 Edit Connection Information
= render 'form'

app/views/ps_connection_informations/index.html.haml
%h1 Print Station Connection Information
= link_to new_ps_connection_information_path, class: 'btn btn-primary' do
  %i.glyphicon.glyphicon-plus
  Connection
%table.table.table-hover
  %thead
    %tr
      %th Print Station
      %th IP Address
      %th Printer Jack
      %th Pharos
      %th
  %tbody
    - @ps_connection_informations.each do |ps_connection_information|
      %tr
        %td= link_to ps_connection_information.print_station.location, print_station_path(ps_connection_information.print_station) unless ps_connection_information.print_station_id.nil?
        %td= link_to ps_connection_information.ip_address, ps_connection_information_path(ps_connection_information)
        %td= ps_connection_information.jack
        %td= ps_connection_information.pharos
        %td
          = link_to edit_ps_connection_information_path(ps_connection_information), class: 'btn-sm' do
            %i.glyphicon.glyphicon-pencil
          = link_to ps_connection_information, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm' do
            %i.glyphicon.glyphicon-trash

app/views/ps_connection_informations/new.html.haml
.text-center  
  %h1 Add Connection Information
= render 'form'

app/views/ps_connection_informations/show.html.haml
.row
  .col-md-2
    .btn-group
      = link_to admin_index_path, class: 'btn btn-sm btn-default' do
        %i.glyphicon.glyphicon-arrow-left
      = link_to edit_ps_connection_information_path(@ps_connection_information), class: 'btn btn-sm btn-default' do
        %i.glyphicon.glyphicon-pencil
%hr
.row
  .col-md-3
    =render 'ps_connection_info'